name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install Node.js and Dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/javierlabs-frontend

      # Set NODE_ENV to production
      - name: Set NODE_ENV to Production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # Build the Vite App
      - name: Build Vite Frontend
        run: npm run build
        working-directory: ./frontend/javierlabs-frontend

      # Deploy the Built App to Azure Static Web Apps
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_OCEAN_0F2F9500F }}
          action: "upload"
          app_location: "./frontend/javierlabs-frontend"
          output_location: "dist" # Built app content directory
          github_id_token: ${{ steps.idtoken.outputs.result }}
