name: CI/CD - Javierlabs-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/AlexBotAPI'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup DotNet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build Project'
        run: |
          mkdir -p './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0993316659C644B1B47A7B2442BEA12C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A8886DE282947819DCAD6FC65C3EF63 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6648E3FC3EE94582BF7E71EB5B06B3F7 }}

      - name: 'Set Environment Variables'
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az functionapp config appsettings set --name Javierlabs-Backend \
              --resource-group Javierlabs-Site_RG \
              --settings \
              JLabsClientId=${{ secrets.JLabsClientId }} \
              JLabsTenantId=${{ secrets.JLabsTenantId }} \
              JLabsClientSecret=${{ secrets.JLabsClientSecret }} \
              JLabsKeyVaultUrl=${{ secrets.JLabsKeyVaultUrl }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'Javierlabs-Backend'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          remote-build: true
          runtime: dotnet
          dotnet-version: '8.0'
