name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Step 2: Make scripts executable
    - name: Make build and deploy scripts executable
      working-directory: ./scripts
      run: |
        chmod +x ./build-frontend.sh
        chmod +x ./build-backend.sh
        
    # Step 3: Build the frontend
    - name: Build Frontend
      working-directory: ./scripts
      run: ./build-frontend.sh
        
    # Step 4: Build the backend
    - name: Build Backend
      working-directory: ./scripts
      run: ./build-backend.sh